services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: intech_atom
      POSTGRES_PASSWORD: intech_atom
      POSTGRES_DB: intech_atom
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
